# Generated by Django 5.0.3 on 2024-04-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_animals', models.ImageField(upload_to='images/', verbose_name='Фотография животного')),
                ('name', models.CharField(max_length=255, verbose_name='Имя животного')),
                ('description', models.TextField(verbose_name='Описание животного')),
                ('category', models.CharField(choices=[('cat', 'кошка'), ('dog', 'собака')], max_length=3, verbose_name='Категория животного')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Животные',
                'verbose_name_plural': 'Животные',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название баннера')),
                ('banner', models.ImageField(upload_to='baner/', verbose_name='Банер')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='Место проведения выставки')),
                ('phone', models.CharField(max_length=25, verbose_name='Телефон организатора')),
                ('duration', models.CharField(max_length=30, verbose_name='Время проведения мероприятия')),
            ],
            options={
                'verbose_name': 'Как к нам добраться',
                'verbose_name_plural': 'Как к нам добраться',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название партнера')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип партнеров')),
                ('partners_link', models.URLField(verbose_name='Ссылка на страницу партнера')),
            ],
            options={
                'verbose_name': 'Партнеры',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Photoreport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photoreport/', verbose_name='Фотоотчет с выставки')),
            ],
            options={
                'verbose_name': 'фотоотчет',
                'verbose_name_plural': 'фотоотчет',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SociaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название социальной сети')),
                ('social_link', models.URLField(verbose_name='Ссылки на социальные сети')),
                ('social_logo', models.ImageField(upload_to='social_links/', verbose_name='Логотип социальной сети')),
            ],
            options={
                'verbose_name': 'Ссылки на социальные сети',
                'verbose_name_plural': 'Ссылки на социальные сети',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя животного, которого забрали')),
                ('story', models.CharField(max_length=255, verbose_name='История пристройства')),
                ('photo', models.ImageField(upload_to='story/', verbose_name='Фотография пристроенного животного')),
            ],
            options={
                'verbose_name': 'Счастливые истории',
                'verbose_name_plural': 'Счастливые истории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EndedShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название выставки')),
                ('image', models.ImageField(upload_to='EndedShow/', verbose_name='Фотография с выставки')),
                ('date', models.DateField(verbose_name='Дата проведения выставки')),
                ('count', models.CharField(max_length=50, verbose_name='Количество животных на выставке')),
                ('animal_housing', models.CharField(max_length=50, verbose_name='Количество пристроенных животных')),
                ('descriptions', models.TextField(verbose_name='Информация по прошедшей выставке')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photoreport', models.ManyToManyField(related_name='photoreport', to='animal_show.photoreport', verbose_name='Фотоотчет с выставки')),
            ],
            options={
                'verbose_name': 'Прошедшие выставки',
                'verbose_name_plural': 'Прошедшие выставки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название выставки')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('info', models.TextField(verbose_name='Информация о выставке')),
                ('quantity', models.CharField(max_length=255, verbose_name='Информация о количестве животных')),
                ('organizer', models.CharField(max_length=255, verbose_name='Информация об организаторе')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('animals', models.ManyToManyField(related_name='animals', to='animal_show.animals', verbose_name='Животные')),
                ('banners', models.ManyToManyField(related_name='banners', to='animal_show.banner', verbose_name='Баннер')),
                ('locations', models.ManyToManyField(related_name='locations', to='animal_show.location', verbose_name='Место проведения')),
                ('partners', models.ManyToManyField(related_name='partners', to='animal_show.partners', verbose_name='Ссылки на страницу партнера')),
                ('social_links', models.ManyToManyField(related_name='social_links', to='animal_show.socialinks', verbose_name='Ссылки на социальные сети')),
                ('stores', models.ManyToManyField(related_name='stores', to='animal_show.story', verbose_name='Счастливые истории')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('user_phone', models.CharField(max_length=25, verbose_name='Телефон пользователя')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='animal_show.show', verbose_name='Выставка')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'db_table': 'app_feedback',
                'ordering': ['id'],
            },
        ),
    ]
