# Generated by Django 5.0.3 on 2024-04-03 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/', verbose_name='Изображения')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название выставки')),
                ('info', models.TextField(verbose_name='Информация о выставке')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('social_links', models.URLField(verbose_name='Ссылки на социальные сети')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публикация')),
                ('result', models.TextField(verbose_name='Итоги выставки')),
                ('banner', models.ManyToManyField(related_name='banner', to='animal_show.image', verbose_name='Баннер')),
                ('last_images', models.ManyToManyField(related_name='last_images', to='animal_show.image', verbose_name='Фотография животных с прошлой выставки')),
                ('logo', models.ManyToManyField(related_name='logo', to='animal_show.image', verbose_name='Логотипы партнеров')),
                ('result_images', models.ManyToManyField(related_name='result_images', to='animal_show.image', verbose_name='Фотография животных по завершению выставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание животного')),
                ('category', models.CharField(choices=[('cat', 'кошка'), ('dog', 'собака')], max_length=3, verbose_name='Категория животного')),
                ('image', models.ManyToManyField(related_name='image', to='animal_show.image', verbose_name='Фотография животных')),
                ('animals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animal_show.show')),
            ],
        ),
    ]
