# Generated by Django 5.0.3 on 2024-04-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images_animal/', verbose_name='Фотографии животного')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='animal_show.animals', verbose_name='Фотоотчет с выставки')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_animals', to='animal_show.image', verbose_name='Прошедшие выставки')),
            ],
        ),
    ]
