# Generated by Django 5.0.3 on 2024-04-03 22:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='banner',
            field=ckeditor.fields.RichTextField(verbose_name='Баннер'),
        ),
    ]
