# Generated by Django 5.0.3 on 2024-04-07 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='animal_show.show', verbose_name='Выставка'),
        ),
    ]
