# Generated by Django 5.0.3 on 2024-04-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['id'], 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='endedshow',
            options={'ordering': ['id'], 'verbose_name': 'Прошедшие выставки', 'verbose_name_plural': 'Прошедшие выставки'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['id'], 'verbose_name': 'Как к нам добраться', 'verbose_name_plural': 'Как к нам добраться'},
        ),
        migrations.AlterModelOptions(
            name='partners',
            options={'ordering': ['id'], 'verbose_name': 'Партнеры', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='photoreport',
            options={'ordering': ['id'], 'verbose_name': 'фотоотчет', 'verbose_name_plural': 'фотоотчет'},
        ),
        migrations.AlterModelOptions(
            name='socialinks',
            options={'ordering': ['id'], 'verbose_name': 'Ссылки на социальные сети', 'verbose_name_plural': 'Ссылки на социальные сети'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['id'], 'verbose_name': 'Счастливые истории', 'verbose_name_plural': 'Счастливые истории'},
        ),
        migrations.RemoveField(
            model_name='show',
            name='locations',
        ),
        migrations.AddField(
            model_name='show',
            name='locations',
            field=models.ManyToManyField(related_name='locations', to='animal_show.location', verbose_name='Место проведения'),
        ),
    ]
