# Generated by Django 5.0.3 on 2024-04-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0002_alter_feedback_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='slug',
        ),
    ]
