# Generated by Django 5.0.3 on 2024-04-11 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0002_image_animalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalimage',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='animal_show.animals', verbose_name='Животное'),
        ),
        migrations.AlterField(
            model_name='animalimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_animals', to='animal_show.image', verbose_name='Другие фотографии животного'),
        ),
    ]
