# Generated by Django 5.0.3 on 2024-04-03 22:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0002_alter_show_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='animals',
            field=ckeditor.fields.RichTextField(verbose_name='Фотография животных'),
        ),
        migrations.AlterField(
            model_name='show',
            name='last_images',
            field=ckeditor.fields.RichTextField(verbose_name='Фотография животных с прошлой выставки'),
        ),
        migrations.AlterField(
            model_name='show',
            name='logo',
            field=ckeditor.fields.RichTextField(verbose_name='Логотипы партнеров'),
        ),
        migrations.AlterField(
            model_name='show',
            name='result_images',
            field=ckeditor.fields.RichTextField(verbose_name='Фотография животных по завершению выставки'),
        ),
    ]
