# Generated by Django 5.0.3 on 2024-04-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0003_remove_feedback_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
