# Generated by Django 5.0.3 on 2024-04-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0004_feedback_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='app_feedback',
        ),
    ]
