# Generated by Django 5.0.3 on 2024-04-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_show', '0005_alter_feedback_slug_alter_feedback_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='feedback',
            table=None,
        ),
    ]
